### ISSUE TITLE
Unstable output

### ISSUE THREAD

**Issue by linghuccc** [nand2/evm-browser#11]
Using web browser, can open below page:
        https://0xda1dfA22a2a82172c7Ed2F7501B40A2c888CED93.sep.w3link.io/greeting

But using EVM browser, below page displays nothing:
        web3://0xda1dfA22a2a82172c7Ed2F7501B40A2c888CED93:11155111/greeting 

![evm](https://github.com/user-attachments/assets/e49c5559-e069-45e9-ac14-010b05e4ec5b)

But in my earlier check, the page displayed the message correctly.

**Comment by nand2** [comment]
Hi!

Sorry I missed your bug report.
This bug is due to the bug https://github.com/web3-protocol/evm-browser/issues/9 where all chain number above 65000 will not work. This is a bug related to electron, in which I cannot do much unfortunately.

For testnet, if you need to test on EVM browser, you should use Holesky (official Ethereum testnet), which have a chain id of 17000, which work ok.
